- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: installing_nodejs

- name: creating user and directory
  ansible.builtin.import_role:
    name: common
    tasks_from: creating_user_and_directory

- name: "downloading the {{component}} files and archiveing"
  ansible.builtin.import_role:
    name: common
    tasks_from: downloading_unarchiving

- name: Installing npm dependencies
  community.general.npm:
    name: npm
    path: /app

- name: copying the user.service
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service


- name: daemon reload user
  ansible.builtin.systemd:
    daemon_reload: true
    name: user

- name: enabling the catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: enabling_starting_service
    

- name: setting up the mongodb repo file
  ansible.builtin.import_role:
    name: common
    tasks_from: mongoclient


- name: loading the schema
  ansible.builtin.import_role:
    name: common
    tasks_from: loadschema
    


