- name: disabling the defauly mysql
  ansible.builtin.command: yum module disable mysql -y 
- name: setting up the repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
- name: installing the mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed
- name: enabling and starting the mqsql
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
- name: changing the password of the mqsql
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1