- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: installing_nodejs

- name: printing the version
  ansible.builtin.debug:
    msg: "version from ansble is {{ version }}"

- name: creating user and directory
  ansible.builtin.import_role:
    name: common
    tasks_from: creating_user_and_directory

- name: downloading the catalogue files and archiveing
  ansible.builtin.import_role:
    name: common
    tasks_from: downloading_unarchiving

- name: Installing npm dependencies
  community.general.npm:
    name: npm
    path: /app

# - name: copying the catalogue.service
#   ansible.builtin.copy:
#     src: catalogue.service
#     dest: /etc/systemd/system/catalogue.service

- name: templating the catalogue.service   #If we have the variables in the config file, we have to put that config file in the templates folder in ansible roles , so that it can fetch the values dynamically
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service


- name: daemon reload catalogue
  ansible.builtin.systemd:
    daemon_reload: true
    name: catalogue

- name: enabling the catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: enabling_starting_service
    

- name: setting up the mongodb repo file
  ansible.builtin.import_role:
    name: common
    tasks_from: mongoclient


# - name: loading the schema
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: loadschema