
- name: setting up the mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing the mongodbshell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
